#lang racket

(provide (all-defined-out))

(define git-flags
  (string-join
   '("-I/home/hebi/benchmark/git"
     "-DGIT_HOST_CPU=\"x86_64\""
     "-DHAVE_ALLOCA_H"
     "-DUSE_CURL_FOR_IMAP_SEND"
     "-DSHA1_DC"
     "-DSHA1DC_NO_STANDARD_INCLUDES"
     "-DSHA1DC_INIT_SAFE_HASH_DEFAULT=0"
     "-DSHA1DC_CUSTOM_INCLUDE_SHA1_C=\"cache.h\""
     "-DSHA1DC_CUSTOM_INCLUDE_UBC_CHECK_C=\"git-compat-util.h\""
     "-DHAVE_PATHS_H"
     "-DHAVE_DEV_TTY"
     "-DHAVE_CLOCK_GETTIME"
     "-DHAVE_CLOCK_MONOTONIC"
     "-DHAVE_GETDELIM"
     "-DFREAD_READS_DIRECTORIES"
     "-DNO_STRLCPY"
     "-DSHELL_PATH=\"/bin/sh\""
     "-DPAGER_ENV=\"LESS=FRX LV=-c\""
     )
   " "))

(define ffmpeg-flags
  (string-join
   '("-I/home/hebi/benchmark/FFmpeg"
     "-D_ISOC99_SOURCE"
     "-D_FILE_OFFSET_BITS=64"
     "-D_LARGEFILE_SOURCE"
     "-D_POSIX_C_SOURCE=200112"
     "-D_XOPEN_SOURCE=600"
     "-DPIC"
     "-DZLIB_CONST"
     "-DHAVE_AV_CONFIG_H"
     "-std=c11"
     "-fomit-frame-pointer"
     "-fPIC"
     "-pthread"
     "-D_REENTRANT"
     "-I/usr/include/SDL2"
     "-fno-math-errno"
     "-fno-signed-zeros"
     "-fno-tree-vectorize"
     "-fdiagnostics-color=auto"
     )
   " "))
(define vim-flags
  (string-join
   '("-I/home/hebi/benchmark/vim"
     "-I/home/hebi/benchmark/vim/src"
     "-I/home/hebi/benchmark/vim/src/proto"
     "-DHAVE_CONFIG_H"
     "-DFEAT_GUI_ATHENA"
     "-U_FORTIFY_SOURCE"
     "-D_FORTIFY_SOURCE=1"
     ) " "))

(define linux-flags
  (string-join
   '("-nostdinc"
     "-isystem"
     "/usr/lib/clang/5.0.1/include"
     "-I/home/hebi/benchmark/linux/arch/x86/include"
     "-I/home/hebi/benchmark/linux/arch/x86/include/generated"
     "-I/home/hebi/benchmark/linux/include"
     "-I/home/hebi/benchmark/linux/arch/x86/include/uapi"
     "-I/home/hebi/benchmark/linux/arch/x86/include/generated/uapi"
     "-I/home/hebi/benchmark/linux/include/uapi"
     "-I/home/hebi/benchmark/linux/include/generated/uapi"
     "-include"
     "/home/hebi/benchmark/linux/include/linux/kconfig.h"
     "-D__KERNEL__"
     "-DCONFIG_CC_STACKPROTECTOR"
     "-Qunused-arguments"
     "-Wall"
     "-Wundef"
     "-Wstrict-prototypes"
     "-Wno-trigraphs"
     "-fno-strict-aliasing"
     "-fno-common"
     "-fshort-wchar"
     "-Werror-implicit-function-declaration"
     "-Wno-format-security"
     "-std=gnu89"
     "-fno-PIE"
     "-mno-sse"
     "-mno-mmx"
     "-mno-sse2"
     "-mno-3dnow"
     "-mno-avx"
     "-m64"
     "-mno-80387"
     "-mstack-alignment=8"
     "-mtune=generic"
     "-mno-red-zone"
     "-mcmodel=kernel"
     "-funit-at-a-time"
     "-DCONFIG_AS_CFI=1"
     "-DCONFIG_AS_CFI_SIGNAL_FRAME=1"
     "-DCONFIG_AS_CFI_SECTIONS=1"
     "-DCONFIG_AS_FXSAVEQ=1"
     "-DCONFIG_AS_SSSE3=1"
     "-DCONFIG_AS_CRC32=1"
     "-DCONFIG_AS_AVX=1"
     "-DCONFIG_AS_AVX2=1"
     "-DCONFIG_AS_SHA1_NI=1"
     "-DCONFIG_AS_SHA256_NI=1"
     "-pipe"
     "-Wno-sign-compare"
     "-fno-asynchronous-unwind-tables"
     "-O2"
     "-Wframe-larger-than=2048"
     "-fstack-protector-strong"
     "-Wno-format-invalid-specifier"
     "-Wno-gnu"
     "-Wno-address-of-packed-member"
     "-Wno-tautological-compare"
     "-mno-global-merge"
     "-no-integrated-as"
     "-Wno-unused-const-variable"
     "-fomit-frame-pointer"
     "-Wdeclaration-after-statement"
     "-Wno-pointer-sign"
     "-fno-strict-overflow"
     "-fno-stack-check"
     "-Werror=implicit-int"
     "-Werror=strict-prototypes"
     "-Werror=date-time"
     "-Werror=incompatible-pointer-types"
     "-Wno-initializer-overrides"
     "-Wno-unused-value"
     "-Wno-format"
     "-Wno-sign-compare"
     "-Wno-format-zero-length"
     "-Wno-uninitialized"
     "-DKBUILD_BASENAME=\\\"\\\""
     "-DKBUILD_MODNAME=\\\"\\\""
     )
   " "))

(define openssl-flags
  (string-join
   '("-I/home/hebi/benchmark/openssl"
     "-I/home/hebi/benchmark/openssl/crypto"
     "-I/home/hebi/benchmark/openssl/crypto/include"
     "-I/home/hebi/benchmark/openssl/include"
     "-pthread"
     "-m64"
     "-Qunused-arguments"
     "-fPIC"
     "-DDSO_DLFCN"
     "-DHAVE_DLFCN_H"
     "-DNDEBUG"
     "-DOPENSSL_NO_STATIC_ENGINE"
     "-DOPENSSL_PIC"
     "-DOPENSSL_CPUID_OBJ"
     "-DOPENSSL_IA32_SSE2"
     "-DOPENSSL_BN_ASM_MONT"
     "-DOPENSSL_BN_ASM_MONT5"
     "-DOPENSSL_BN_ASM_GF2m"
     "-DSHA1_ASM"
     "-DSHA256_ASM"
     "-DSHA512_ASM"
     "-DRC4_ASM"
     "-DMD5_ASM"
     "-DAES_ASM"
     "-DVPAES_ASM"
     "-DBSAES_ASM"
     "-DGHASH_ASM"
     "-DECP_NISTZ256_ASM"
     "-DX25519_ASM"
     "-DPADLOCK_ASM"
     "-DPOLY1305_ASM"
     "-DOPENSSL_USE_NODELETE"
     "-DL_ENDIAN"
     "-DOPENSSLDIR=\"/usr/local/ssl\""
     "-DENGINESDIR=\"/usr/local/lib/engines-1.1\""

     ;; /home/hebi/benchmark/openssl/crypto/asn1
     "-I/home/hebi/benchmark/openssl/crypto/modes"
     "-I/home/hebi/benchmark/openssl/crypto/asn1"
     "-I/home/hebi/benchmark/openssl/crypto/evp"
     "-DOPENSSL_THREADS"
     "-D_REENTRANT"
     "-DDSO_DLFCN"
     "-DHAVE_DLFCN_H"
     "-m64"
     "-DL_ENDIAN"
     "-DOPENSSL_IA32_SSE2"
     "-DOPENSSL_BN_ASM_MONT"
     "-DOPENSSL_BN_ASM_MONT5"
     "-DOPENSSL_BN_ASM_GF2m"
     "-DRC4_ASM"
     "-DSHA1_ASM"
     "-DSHA256_ASM"
     "-DSHA512_ASM"
     "-DMD5_ASM"
     "-DAES_ASM"
     "-DVPAES_ASM"
     "-DBSAES_ASM"
     "-DWHIRLPOOL_ASM"
     "-DGHASH_ASM"
     "-DECP_NISTZ256_ASM"

     )
   " "))

